---
regions:
  - name: example-region
    hostSupervisor:
      name: example-supervisor
      configuration:
        enabled: true
        port: 8080
    clientSupervisors:
      - example-supervisor
__system:
  uiplugin1: registry.local/myservice-ui:0.0.0
