BASE_NAME := myservice

COMPONENT_NAME := vcf-service-$(BASE_NAME)

NAME := myservice.broadcom.com

VCFA_CUSTOMER_VERSION ?= 0.1.0
VCFA_CUSTOMER_PATCH   ?= 0
BUILD_NUMBER          ?= 0

VERSION                    := $(VCFA_CUSTOMER_VERSION).$(VCFA_CUSTOMER_PATCH).$(BUILD_NUMBER)
VERSION_WITHOUT_BUILD_NUMBER := $(VCFA_CUSTOMER_VERSION).$(VCFA_CUSTOMER_PATCH)
VERSION_TAG                := $(VERSION)
VERSION_WITH_BUILD_NUMBER_PATH := $(VERSION_WITHOUT_BUILD_NUMBER)-$(BUILD_NUMBER)

VCFA_PLUGIN_DIR ?= ../vcfa-plugin

UI_PLUGINS := uiplugin1=$(VCFA_PLUGIN_DIR)/dist/plugin.zip=myservice-ui:$(VERSION)
